### ISSUE TITLE
[Q] How do you change a string of text?

### ISSUE THREAD

**Issue by ThunderGemios10** [upcFrost/SDR2_translate#5]
I just tried out the tool. I wasn't able to change the string of text..

**Comment by upcFrost** [comment]
Hi, sorry, didn't see the issue opened. 

About the translation - in general it goes like this. First open the .lin file, you will get a number of script steps. You can go step by step, changing lines when they appear in the script, or you can switch to the "strings" tab to skip the script-related part and see only the text. After changing the line, press the set line button. After finishing with the file, save it somewhere. 

There's some more tricks like how to add the new line (like, completely new one), but it takes to modify the script flow  (add or remove ops)
